apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["10000"]