service: todos

provider:
  name: kubeless
  runtime: nodejs6

plugins:
  - serverless-kubeless

functions:
  app-create:
    handler: todos-create.create
    events:
      - http:
          path: /create
  app-read-all:
    handler: todos-read-all.readAll
    events:
      - http:
          path: /read-all
  app-read-one:
    handler: todos-read-one.readOne
    events:
      - http:
          path: /read
  app-update:
    handler: todos-update.update
    events:
      - http:
          path: /update
  app-delete:
    handler: todos-delete.delete
    events:
      - http:
          path: /delete
  app-event-pub:
    handler: event-pub.publish
    events:
      - http:
          path: /publish-event
  app-event-sub:
    handler: event-sub.subscribe
    events:
      - trigger: 'event_test'
